export const portfolio = [
  {
    year: "2025",
    label: "Renaissance",
    projects: [
      {
        name: "Kimirica",
        tags: "brand identity, packaging",
        img: "/images/clients/kimirica.svg",
        url: "https://kimirica.com/",
      },
      {
        name: "Ozone Group",
        tags: "campaign, art direction",
        img: "/images/clients/ozone-group.png",
        url: "https://ozonegroup.com/",
      },
      {
        name: "Jagran Lakecity University",
        tags: "brand strategy, social media",
        img: "/images/clients/jlu.png",
        url: "https://jlu.edu.in/",
      },
      {
        name: "Shrewsbury International School India",
        tags: "brand identity, campaign",
        img: "/images/clients/shrewsbury.svg",
        url: "https://shrewsburyindia.in/",
      },
      {
        name: "Bombay Hospital",
        tags: "brand identity, web",
        img: "/images/clients/bombay-hospital.png",
        url: "https://www.bombayhospitalindore.com/",
      },
      {
        name: "ISAK Fragrances",
        tags: "brand identity, packaging",
        img: "/images/clients/isak.png",
        url: "https://www.isakfragrances.com/",
      },
      {
        name: "Skyra",
        tags: "social media, content",
        img: "/images/clients/skyra.webp",
        url: "https://skyra.ind.in/",
      },
      {
        name: "Stone Galaxy",
        tags: "web design, branding",
        img: "/images/work/work_008.jpeg",
        url: "https://www.instagram.com/stonegalaxyindore/",
      },
    ],
  },
  {
    year: "2024",
    label: "Amplify",
    projects: [
      {
        name: "Fayon Kids",
        tags: "social media, art direction",
        img: "/images/clients/fayon-kids.png",
        url: "https://www.fayonkids.com/",
      },
      {
        name: "EO",
        tags: "event branding, campaign",
        img: "/images/work/work_010.jpeg",
        url: "https://www.eonetwork.org/indore",
      },
      {
        name: "Ahilya Skincare",
        tags: "brand identity, packaging",
        img: "/images/clients/ahilya.png",
        url: "https://ahilyalifestyle.com/",
      },
      {
        name: "Denz Label",
        tags: "social media, art direction",
        img: "/images/clients/denz-label.webp",
        url: "https://www.denzlabel.com/",
      },
      {
        name: "Biocule",
        tags: "brand identity, web",
        img: "/images/clients/biocule.png",
        url: "https://biocule.com/",
      },
      {
        name: "Nuvae",
        tags: "brand identity, packaging",
        img: "/images/clients/nuvae.png",
        url: "https://www.nuvae.in/",
      },
      {
        name: "Parag Bathroom",
        tags: "campaign, social media",
        img: "/images/work/work_015.jpeg",
        url: "https://prayagindia.com/",
      },
      {
        name: "Solar EV",
        tags: "brand identity, web design",
        img: "/images/clients/evayve.png",
        url: "https://evayve.com/",
      },
    ],
  },
  {
    year: "2023",
    label: "Compose",
    projects: [
      {
        name: "The House of Migo",
        tags: "brand identity, social media",
        img: "/images/clients/house-of-migo.jpg",
        url: "https://www.thehouseofmigo.com/",
      },
      {
        name: "POSH Tablewear",
        tags: "art direction, packaging",
        img: "/images/clients/theposh.webp",
        url: "https://theposh.in/",
      },
      {
        name: "Kimirica Hunter",
        tags: "brand identity, campaign",
        img: "/images/clients/kimirica.svg",
        url: "https://kimirica.com/",
      },
      {
        name: "Omrae",
        tags: "brand identity, packaging",
        img: "/images/work/work_020.jpeg",
        url: "https://omrae.com/",
      },
      {
        name: "Madhuri Oil",
        tags: "campaign, social media",
        img: "/images/clients/madhuri-oil.png",
        url: "https://madhurioils.com/",
      },
      {
        name: "Trikaal",
        tags: "brand identity, social media",
        img: "/images/clients/trikaay.png",
        url: "https://trikaay.in/",
      },
      {
        name: "Roccia",
        tags: "art direction, content",
        img: "/images/work/work_023.jpeg",
        url: "#",
      },
    ],
  },
  {
    year: "2022",
    label: "Ignite",
    projects: [
      {
        name: "Davesmen",
        tags: "brand identity, social media",
        img: "/images/clients/davesmen.png",
        url: "https://www.davesmenindia.com/",
      },
      {
        name: "MUN 20",
        tags: "event branding, campaign",
        img: "/images/clients/iimun.png",
        url: "https://iimun.in/",
      },
      {
        name: "YFLO",
        tags: "event branding, art direction",
        img: "/images/work/work_001.jpeg",
        url: "https://ficciflo.org/",
      },
      {
        name: "Abhyuday",
        tags: "campaign, social media",
        img: "/images/clients/abhyuday.png",
        url: "https://www.abhyudayiitb.org/",
      },
      {
        name: "Madanlal Chagganlal",
        tags: "brand identity, packaging",
        img: "/images/clients/madanlal.png",
        url: "https://madanlalchhaganlal.com/",
      },
      {
        name: "Harshvardhan Ishipal",
        tags: "brand identity, content",
        img: "/images/clients/harshvardhan.jpg",
        url: "https://harshvardhanishipal.com/",
      },
      {
        name: "Mittal Craftworks",
        tags: "brand identity, web design",
        img: "/images/clients/mittal-craftworks.png",
        url: "https://mittalgroup.com/",
      },
    ],
  },
  {
    year: "2021",
    label: "Genesis",
    projects: [
      {
        name: "Rahul Garg",
        tags: "personal branding, content",
        img: "/images/work/work_006.jpeg",
        url: "#",
      },
      {
        name: "Edible Jelly",
        tags: "brand identity, packaging",
        img: "/images/work/work_007.jpeg",
        url: "#",
      },
      {
        name: "Akash Hospital",
        tags: "brand identity, web",
        img: "/images/clients/akash-hospital.png",
        url: "https://www.akashhospital.co.in/",
      },
      {
        name: "Augain",
        tags: "brand identity, social media",
        img: "/images/work/work_009.jpeg",
        url: "#",
      },
      {
        name: "SOVI & TYDI",
        tags: "brand identity, packaging",
        img: "/images/clients/soviandtydi.png",
        url: "https://soviandtydi.com/",
      },
      {
        name: "Teeth Hub",
        tags: "brand identity, social media",
        img: "/images/clients/teethhub.webp",
        url: "https://teethhub.in/",
      },
    ],
  },
];
